name: mono_localization
description: mono_localization is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.8.5

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ^6.3.0
  archive: ^3.4.9
  args: ^2.4.2
  dart_style: ^2.3.4
  http: ">=0.13.0 <2.0.0"
  intl: ">=0.17.0 <0.19.0"
  path: ^1.8.3
  petitparser: ">=4.0.0 <7.0.0"
  yaml: 3.1.2

dev_dependencies:
  build_runner: 2.4.7
  mockito: 5.4.3
  test: 1.24.9
  very_good_analysis: ^5.1.0

flutter_intl:
  enabled: true
  base_class_path: lib/test/library_base.dart
  base_class_name: LocalizationLibraryBase
  structure:
    - library:
        library_name: BaseLibrary
        base: true
        arb_dir: lib/test/base_library/arb/
        output_dir: lib/test/base_library/
        widget_path: lib/test/base_library/base_library_localization_provider.dart
        widget_name: BaseLibraryLocalizationProvider
    - library:
        library_name: OtherBaseLibrary
        base: true
        arb_dir: lib/test/other_base_library/arb/
        output_dir: lib/test/other_base_library/
        widget_path: lib/test/other_base_library/other_base_library_localization_provider.dart
        widget_name: OtherBaseLibraryLocalizationProvider
    - library:
        library_name: NonBaseLibrary
        arb_dir: lib/test/non_base_library/arb/
        output_dir: lib/test/non_base_library/
        widget_path: lib/test/non_base_library/non_base_library_localization_provider.dart
        widget_name: NonBaseLibraryLocalizationProvider
