name: mono_localization
description: mono_localization is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.8.5

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^3.4.9
  args: ^2.4.2
  dart_style: ^2.3.2
  http: ">=0.13.0 <2.0.0"
  intl: ">=0.17.0 <0.19.0"
  path: ^1.8.3
  petitparser: ">=4.0.0 <7.0.0"
  yaml: 3.1.2

dev_dependencies:
  build_runner: 2.4.7
  mockito: 5.4.3
  test: 1.24.9