name: mono_localization
description: mono_localization is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.8.6

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  dart_style: 3.0.1
  http: ">=1.4.0"
  intl: ">=0.20.2"
  path: ^1.9.1
  petitparser: ">=6.1.0"
  yaml: 3.1.3

dev_dependencies:
  build_runner: 2.4.15
  mockito: 5.4.6
  test: 1.25.15